language: ruby

env:
  - PUPPET_VERSION=4.2.2
  - PUPPET_VERSION=4.2.1
  - PUPPET_VERSION=4.2.0
  - PUPPET_VERSION=4.1.0
  - PUPPET_VERSION=4.0.0

rvm:
  - 2.2.3
  - 2.2.2
  - 2.2.1
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3

script:
  - 'bundle exec rake spec'
